title: Zain Ul Islam Siddiqui
logo: logo image
description: Embedded Hardware Engineer | PCB Design | IoT & Wireless Systems | Building Real Hardware Projects
show_downloads: true
theme: jekyll-theme-minimal
